### ISSUE TITLE
No requrements in setup.py file. no module tabulate

### ISSUE THREAD

**Issue by blacksailer** [vra/flopth#1]
Hello!
Trying your package. encounter this:
```
ModuleNotFoundError: No module named 'tabulate'
```

**Comment by vra** [comment]
Hi @blacksailer ,
Thanks for trying this program. This is a bug, I forget add required packages in `setup.py`. I have fixed this issue in [this commit](https://github.com/vra/flopth/commit/471d0190cad2462ba52d707e4243bb75d6bb946a). Please update this package to check if everything is okay.
