### ISSUE TITLE
Useful warning is commented

### ISSUE THREAD

**Issue by blacksailer** [vra/flopth#2]
Tested on mine model, and got little flops. Figured that operation was not supported. Indeed. 

This line is useful, I think it should be there.

https://github.com/vra/flopth/blob/67efae3d793008443840faab72b0627f56b16c1c/flopth/helper.py#L21

**Comment by vra** [comment]
Hi @blacksailer .
Thanks for pointing out this issue. I have fixed it (just uncomment this line of code) in latest version. Please install it by pip. Thanks again for trying this program.
